server:
  name: "database"
  net: 2
  http_server_addr: ":8118"
  fix_charset: true
  prometheus_push_gateway: ""
notice:
  webhook_lark_err: ""
  sentry_dsn: ""
chain:
  ckb_url: "" #"https://testnet.ckb.dev/"
  index_url: "" #"https://testnet.ckb.dev/indexer"
  current_block_number: 1927285 # 4872287: mainnet 1927285: testnet
  confirm_num: 4 # confirm nums before written into DB
  concurrency_num: 200
origins:
  - "localhost:3000"
snapshot:
  open: true
  concurrency_num: 100
  confirm_num: 4
  snapshot_num: 500
db:
  mysql:
    log_mode: true
    addr: ""
    user: ""
    password: ""
    db_name: ""
    max_open_conn: 100
    max_idle_conn: 50
cache:
  redis:
    addr: ""
    password: ""
    db_num: 17
gecko_ids:
  - "nervos-network"
  - "ethereum"
  - "bitcoin"
  - "tron"
  - "_wx_cny_"
  - "binancecoin"
  - "matic-network"