name: CD
on: 
  workflow_run: 
    workflows: [CI]
    types: 
      - completed
jobs:
  deploy-dev:
    environment: Dev
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && github.ref != 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Download Filename
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          name: filename
      - name: Expose Filename
        run: echo "ARTIFACT_FILENAME=$(cat filename)" > $GITHUB_ENV
      - name: Download Artifct
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          name: ${{ env.ARTIFACT_FILENAME }}
      - name: Stop Service
        run: ssh ${{ vars.SSH_HOST }} 'supervisorctl stop das_database_svr'
      - name: SCP
        run: scp das_database_server das_test:${{ vars.TARGET_FOLDER }}/das_database_server
      - name: Restart Service
        run: ssh ${{ vars.SSH_HOST }} 'supervisorctl restart das_database_svr'

  deploy-prod:
    environment: Prod
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Download Filename
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          name: filename
      - name: Expose Filename
        run: echo "ARTIFACT_FILENAME=$(cat filename)" > $GITHUB_ENV
      - name: Download Artifct
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          name: ${{ env.ARTIFACT_FILENAME }}
      - name: Stop Service
        run: ssh ${{ vars.SSH_HOST }} 'supervisorctl stop das_database_svr'
      - name: SCP
        run: scp das_database_server ${{ vars.SSH_HOST }}:${{ vars.TARGET_FOLDER }}/das_database_server
      - name: Restart Service
        run: ssh ${{ vars.SSH_HOST }} 'supervisorctl restart das_database_svr'