name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  cd:
    runs-on: sg
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download Artifct
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          name: das_database_server
      - name: Deploy
        run: |
          host_name=""
          branch=$(cat branch.txt)
          if [[ "$branch" == "refs/heads/dev" ]]; then
            host_name="backendtest"
          elif [[ "$branch" == "refs/heads/test3" ]]; then
            host_name="backendtest3"
          else
            echo "Skipping build and deploy for branch ${branch}"
            exit 1
          fi
          
          ssh root@"$host_name" 'supervisorctl stop das_database_svr'
          rsync -a das_database_server root@"$host_name":/mnt/das/server/das_database/das_database_server
          ssh root@"$host_name" 'chmod +x /mnt/das/server/das_database/das_database_server && supervisorctl start das_database_svr'