name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  cd:
    runs-on: sg
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download Artifct
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          name: das_database_server
      - name: Deploy
        run: |
          svr_host = ""
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            svr_host = "backendtest"
          elif [[ "${{ github.ref }}" == "refs/heads/test3" ]]; then
            svr_host = "backendtest3"
          else
            echo "Skipping build and deploy for branch ${GITHUB_REF}"
            exit 1
          fi
          
          ssh root@backendtest 'supervisorctl stop das_database_svr'
          rsync -a das_database_server root@"${svr_host}":/mnt/das/server/das_database/das_database_server
          ssh root@"${svr_host}" 'chmod +x /mnt/das/server/das_database/das_database_server && supervisorctl start das_database_svr'