name: CI

on:
  push:
    branches:
      - dev
      - test3

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: false
      - name: Build
        run: make default && echo "${{ github.ref }}" > bin/linux/branch.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: das_database_server
          path: |
            bin/linux/das_database_server
            bin/linux/branch.txt
